name: Build and test

on: [ push ]

env:
  BUILD_TYPE: Release

jobs:
  check-styling:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Verify formatting
        uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: '16'
          check-path: '.'

      - name: Verify copyright
        run: python ./scripts/check_copyright.py

  build-and-test:
    runs-on: ubuntu-latest
    needs: check-styling
#    strategy:
#      matrix:
#        compiler_c: [gcc] #, clang]
#        include:
#          - compiler_c: gcc
#            compiler_cpp: g++

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run:
          sudo apt install mesa-common-dev libglu1-mesa-dev freeglut3-dev libc++-dev

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.6.*
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'

      - name: Configure CMake
        env:
          CC: ${{ matrix.compiler_c }}
          CXX: ${{ matrix.compiler_cpp }}
        run: cmake -DCMAKE_PREFIX_PATH=$QT_ROOT_DIR -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build  -j 4 --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}