name: Build and test

on: [ push ]

env:
  BUILD_TYPE: Release

jobs:
  check-styling:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Verify formatting
        uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: '16'
          check-path: '.'

      - name: Verify copyright
        run: python ./scripts/check_copyright.py

      - name: Verify includes
        run: python ./scripts/check_includes.py

  build-and-test-linux:
    runs-on: ubuntu-latest
    needs: check-styling

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run:
          sudo apt install mesa-common-dev libglu1-mesa-dev freeglut3-dev libc++-dev

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.6.*
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'

      - name: Configure CMake
        env:
          CC: ${{ matrix.compiler_c }}
          CXX: ${{ matrix.compiler_cpp }}
        run: cmake -DCMAKE_PREFIX_PATH=$QT_ROOT_DIR -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build  -j 4 --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}

  build-and-test-windows:
    runs-on: windows-latest
    needs: check-styling

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.6.*
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'

      - name: Configure CMake
        env:
          CC: ${{ matrix.compiler_c }}
          CXX: ${{ matrix.compiler_cpp }}
        run: cmake -DCMAKE_PREFIX_PATH=$QT_ROOT_DIR -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build -j4 --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}

  build-and-test-macos:
    runs-on: macos-latest
    needs: check-styling

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.6.*
          host: 'mac'
          target: 'desktop'
          arch: 'clang_64'

      - name: Configure CMake
        env:
          CC: ${{ matrix.compiler_c }}
          CXX: ${{ matrix.compiler_cpp }}
        run: cmake -DCMAKE_PREFIX_PATH=$QT_ROOT_DIR -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build  -j 4 --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}