name: Sonarcloud analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  BUILD_TYPE: Release

jobs:
  sonar-analysis:
    runs-on: ubuntu-latest
    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory # Directory where build-wrapper output will be placed

    steps:
      - uses: actions/checkout@v4

      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v2
        id: cpu-cores

      - name: Install dependencies
        run:
          sudo apt install gcovr

      - name: Install Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.6.*
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'
          cache: true

      - name: Run build-wrapper
        run: |
          mkdir build
          cmake -DCMAKE_PREFIX_PATH=$QT_ROOT_DIR -B ${{github.workspace}}/build -DCMAKE_C_FLAGS=--coverage -DCMAKE_CXX_FLAGS=--coverage
          build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} cmake --build build/ --config Debug -j ${{ steps.cpu-cores.outputs.count }}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}

      - name: Collect coverage in xml
        run: |
          gcovr --sonarqube > coverage.xml


      - name: Run sonar-scanner
        uses: sonarsource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            --define sonar.cfamily.compile-commands=${{ env.BUILD_WRAPPER_OUT_DIR }}/compile_commands.json
            --define sonar.coverageReportPaths=coverage.xml